### PR TITLE
Hotfix/filebrowser cli config fix

### PR DESCRIPTION
**Pull request by noxify**
Fix for #44

### CODE REVIEW

**Comment by noxify** [comment]
@bihlmaierh - please check :)

**Comment by Froxz** [comment]
```[ErrorException]
  call_user_func() expects parameter 1 to be a valid callback, no array or string given



Script php artisan clear-compiled handling the pre-update-cmd event returned with an error



  [RuntimeException]
  Error Output:``
After update new error.

**Comment by noxify** [comment]
Did you update the `config/admin.php` with the new arguments?
https://github.com/Pseudoagentur/soa-sentinel/pull/46/files#diff-8c6999c6977539530459d4be9a3a5150R68

**Comment by Froxz** [comment]
@noxify to late))))) sorry for my mistake. Yes working like a charm)))

**Comment by noxify** [comment]
perfect :)

**Pull request merged**
